# Generated by Django 4.0.1 on 2022-01-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Renda')),
                ('bio', models.TextField(verbose_name='Sobre')),
            ],
        ),
    ]
