# Generated by Django 4.0.1 on 2022-02-15 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_person_dt_nasc'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dt_cadastro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
