# Generated by Django 4.0 on 2022-02-22 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_vendas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desconto_p', models.IntegerField()),
                ('descricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_venda', to='clientes.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=7)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imposto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.person')),
                ('produtos', models.ManyToManyField(related_name='vendas', through='clientes.ProdutoVenda', to='clientes.Produto')),
            ],
        ),
        migrations.DeleteModel(
            name='Vendas',
        ),
        migrations.AddField(
            model_name='produtovenda',
            name='numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_venda', to='clientes.venda'),
        ),
    ]
