# Generated by Django 4.0 on 2022-02-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_person_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='dt_cadastro',
        ),
    ]
